name: telegram notify
on:
  pull_request:
    types: [closed]
#  push:
#    branches: [main]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: The ${{ github.event_name }} event triggered first step. Description is ${{github.event.pull_request.body}}, pr_num ${{github.event.number}}