name: telegram message
on:
  push:
    branches: [main]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      if: always()
      with:
        chat: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}