name: Run builds

on:
  schedule:
    - cron: '40 18 * * 1-6'
  workflow_dispatch:

#jobs:
#  job1:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Test
#        run: echo "Hello World"

jobs:
  branch_matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - id: set-matrix
        run: |
          python -m pip install --upgrade pip
          pip install requests
          output=$(python3 api_work.py)
          echo ${{fromJson($output)}}
#          echo "::set-output name=matrix::$(python3 api_work.py)"

#  test_echo:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix: ${{fromJson(needs.branch_matrix.outputs.matrix)}}
#
#    steps:
#      - name: Test echo
#        run: echo ${{ matrix.branch }}

#  integration_test:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [ 3.7 ]
#    #      matrix: ${{fromJson(needs.branch_matrix.outputs.matrix)}}
#
#    steps:
#      - name: Checkout branch
#        uses: actions/checkout@v2
##        with:
##          ref: ${{ matrix.branch }}
#      - name: Set up Python ${{ matrix.python-version }}
#        uses: actions/setup-python@v2
#        with:
#          python-version: ${{ matrix.python-version }}
#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install pytest
#      - name: Test with pytest
#        run: |
#          pytest -s test