name: Run builds

on:
  workflow_dispatch:

jobs:
  integration_test:
    runs-on: [self-hosted, cml, gpu]
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Test with pytest
        run: |
          pytest -s test
